<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ config('app.name', 'SmartLoket') }} — Cetak Rekap Laporan</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        @media print {
            body { font-size: 10pt; }
            .no-print { display: none !important; }
            .table { font-size: 9pt; }
            @page { margin: 1.5cm; size: landscape; }
        }
        body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; font-size: 11pt; }
        .header-print { border-bottom: 1px solid #dee2e6; padding-bottom: 10px; margin-bottom: 16px; }
    </style>
</head>
<body class="p-4">
    @include('partials.kop_surat')

    <div class="header-print d-flex justify-content-between align-items-center">
        <div>
            <h5 class="fw-bold mb-0">LAPORAN REKAPITULASI PELAYANAN PERTANAHAN</h5>
            <small class="text-muted">Kantor Pertanahan Kota Bandar Lampung</small>
        </div>
        <div class="text-end no-print">
            <button onclick="window.print()" class="btn btn-primary btn-sm"><i class="bi bi-printer me-1"></i>Cetak / Simpan PDF</button>
            <button onclick="window.close()" class="btn btn-outline-secondary btn-sm"><i class="bi bi-x-lg me-1"></i>Tutup</button>
        </div>
        <div class="text-end d-none d-print-block">
            <small>Dicetak: {{ now()->format('d/m/Y H:i') }}</small>
        </div>
    </div>

    <div class="mb-3">
        <small class="text-muted">
            Periode: {{ \Carbon\Carbon::parse($startDate)->format('d/m/Y') }} — {{ \Carbon\Carbon::parse($endDate)->format('d/m/Y') }}
            @if(!empty($status)) | Status: {{ $status }} @endif
        </small>
    </div>

    <div class="table-responsive">
        <table class="table table-bordered table-sm align-middle mb-0">
            <thead class="table-light">
                <tr>
                    <th style="width:30px;">No</th>
                    <th>Kode Tiket</th>
                    <th>Tgl Masuk</th>
                    <th>Nama Pemohon</th>
                    <th>NIK</th>
                    <th>Jenis Permohonan</th>
                    <th>Bidang</th>
                    <th>Kelurahan</th>
                    <th>Kecamatan</th>
                    <th>Petugas Loket</th>
                    <th>Tgl Selesai</th>
                    <th>Status</th>
                    <th>Pembetulan</th>
                </tr>
            </thead>
            <tbody>
                @forelse($tikets as $idx => $t)
                    <tr>
                        <td>{{ $idx + 1 }}</td>
                        <td class="fw-bold">{{ $t->kode_tiket }}</td>
                        <td>{{ $t->tanggal_masuk?->format('d/m/Y') }}</td>
                        <td>{{ $t->nama_pemohon }}</td>
                        <td>{{ $t->nik_pemohon ?? '-' }}</td>
                        <td>{{ $t->jenisPermohonan?->kode }} — {{ $t->jenisPermohonan?->nama }}</td>
                        <td class="text-center">{{ $t->bidangTanahs->count() }}</td>
                        <td>{{ $t->kelurahan_desa ?? '-' }}</td>
                        <td>{{ $t->kecamatan ?? '-' }}</td>
                        <td>{{ $t->petugasLoket?->name ?? '-' }}</td>
                        <td>{{ $t->tanggal_selesai?->format('d/m/Y') ?? '-' }}</td>
                        <td><span class="badge bg-{{ $t->status_badge }}">{{ $t->status_label }}</span></td>
                        <td class="text-center">{{ $t->status_pembetulan }}</td>
                    </tr>
                @empty
                    <tr><td colspan="13" class="text-center text-muted py-3">Tidak ada data pada filter ini.</td></tr>
                @endforelse
            </tbody>
            <tfoot>
                <tr class="table-light fw-bold">
                    <td colspan="6" class="text-end">Total: {{ $tikets->count() }} berkas</td>
                    <td colspan="7"></td>
                </tr>
            </tfoot>
        </table>
    </div>

    <div class="mt-4 d-flex justify-content-between">
        <small class="text-muted">Generated by {{ config('app.name') }} &bull; {{ now()->format('d/m/Y H:i:s') }}</small>
    </div>
</body>
</html>